// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

#nullable disable

namespace server.Data.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20221025030944_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("server.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Location = "Initial Location 1",
                            Name = "Initial Todo 1",
                            Status = "scheduled"
                        },
                        new
                        {
                            Id = 2L,
                            Location = "Initial Location 2",
                            Name = "Initial Todo 2",
                            Status = "todo"
                        },
                        new
                        {
                            Id = 3L,
                            Location = "Initial Location 3",
                            Name = "Initial Todo 3",
                            Status = "scheduled"
                        },
                        new
                        {
                            Id = 4L,
                            Location = "Initial Location 4",
                            Name = "Initial Todo 4",
                            Status = "scheduled"
                        },
                        new
                        {
                            Id = 5L,
                            Location = "Initial Location 5",
                            Name = "Initial Todo 5",
                            Status = "todo"
                        },
                        new
                        {
                            Id = 6L,
                            Location = "Initial Location 6",
                            Name = "Initial Todo 6",
                            Status = "todo"
                        },
                        new
                        {
                            Id = 7L,
                            Location = "Initial Location 7",
                            Name = "Initial Todo 7",
                            Status = "todo"
                        },
                        new
                        {
                            Id = 8L,
                            Location = "Initial Location 8",
                            Name = "Initial Todo 8",
                            Status = "scheduled"
                        },
                        new
                        {
                            Id = 9L,
                            Location = "Initial Location 9",
                            Name = "Initial Todo 9",
                            Status = "todo"
                        },
                        new
                        {
                            Id = 10L,
                            Location = "Initial Location 10",
                            Name = "Initial Todo 10",
                            Status = "todo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
